version: "3"
services:
  listings-service:
    build: "./listings-service"
    depends_on:
      - listings-service-db
    volumes:
      - ./listings-service:/opt/app
    environment: 
      - DB_URI=postgresql://root:password@listings-service-db/db?charset=UTF8
  
  listings-service-db:
    image: postgres:12.5-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
      - POSTGRES_DB=db
    ports:
      - 0.0.0.0:7200:5432

  users-service:
    build: "./users-service"
    depends_on:
      - users-service-db
    volumes:
      - ./users-service:/opt/app
    environment: 
      - DB_URI=postgresql://root:password@users-service-db/db?charset=UTF8

  users-service-db:
    image: postgres:12.5-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
      - POSTGRES_DB=db
    ports:
      - 0.0.0.0:7201:5432